### ISSUE TITLE
Polykai theme for visual Studio

### ISSUE THREAD

**Issue by kone9** [adamgraham/polykai-vscode#1]
Hello, I wanted to know if you happen to have this theme for Visual Studio .. Thank you !.

**Comment by adamgraham** [comment]
Yes, I do in fact. This repo has the full list of supported editors: https://github.com/adamgraham/polykai. And specifically, here is the link for the Visual Studio files https://github.com/adamgraham/polykai/tree/master/Visual%20Studio.

**Comment by kone9** [comment]
Thanks!!
![Screenshot_1](https://user-images.githubusercontent.com/12847027/140499739-c7915eff-2b2d-43d5-a0c0-72dc25b29cc4.jpg)
!
